### PR TITLE
PayPal Recurring Payments Support

### PR DESCRIPTION
**Pull request by niofis**
Implemented Recurring Payments for PayPal, also added CultureInvariant format to decimal - string conversions.

### CODE REVIEW

**Comment by davidduffett** [comment]
Looks great - is there any way you can add in an integration test to ensure we get the correct response from the PayPal sandbox?  Do they allow recurring payments in the sandbox?

Just want to ensure if we do any changes it doesn't suddenly break.

**Comment by niofis** [comment]
Thanks!,

These changes where made because I needed them for a project I'm working on (which is currently working in a testing environment), I'll get to write the tests in any change I get.

By the way, PayPal does allow recurring payments in the sandbox.

Regards

**Comment by niofis** [comment]
Hello!, I've just pushed the integration test for recurring paypal recurring payments, please take a look at it any change you get and tell me if it is good enough. 

Regards!

**Comment by davidduffett** [comment]
I see you've done a unit test for the CreateRecurringPaymentsProfile method, but I was rather thinking of an integration test that uses real implementations and communicates with the PayPal sandbox?

Some examples can be found here: https://github.com/davidduffett/Moolah/blob/master/Moolah/Moolah.Specs/PayPal/IntegrationTest.cs

These tests perform an actual request to PayPal and test for an expected response from the sandbox.

Sorry for not being so clear in the beginning!

**Comment by niofis** [comment]
I've created some integration tests that cover the usage of the recurring payments library for PayPal, and moved the unit test into a new code file. 

When you have any change I would appreciate it if you could tell me whether the new tests are compliant with what you where expecting.

Sorry for taking so long.

**Comment by davidduffett** [comment]
No need to apologise, thanks for getting this implemented!

I'm going to go through the changes tonight and tomorrow - there may be a few tweaks I'd like to make, probably nothing major, just so that I understand these recurring payments a bit better (I've never used them).

I'll discuss anything I'd like to change here so you're involved.

Cheers

**Comment by davidduffett** [comment]
OK - after reading about recurring payments I now understand it (I think..).  The only changes I made were to add [Subject] attributes to your integration tests (so they are run by Resharper) and to rename "IsRecurrentPayment" to "IsRecurringPayment" (just seemed to sound nicer and match PayPal's terminology).

Thanks very much for the contribution!  It should be up on Nuget soon.

**Comment by niofis** [comment]
Wow, thank you so much!.

I'm very happy that the changes I made where accepted by you. This is the
first time for me to contribute to an open source project and it feels
great.

If anything else arises feel free to contact me.

Regards!

Enrique

**Pull request merged**
